name: bottom_navigation
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  cart:
    path: ../cart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2



dependency_overrides:
  http: ^0.13.5

