name: core
description: A new Flutter package project.
version: 1.0.0
homepage: www.github.com

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.0
  flutter_screenutil: ^5.9.0
  image_loader: ^1.9.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  rxdart: ^0.27.7
  form_field_validator: ^1.1.0
  dio_builder: ^3.0.1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  json_annotation: ^4.8.1
  custom_progress_button: ^2.0.1
  flutter_spinkit: ^5.2.0
  simple_shared_pref: ^2.0.6
  transition_easy: ^1.0.8
  flutterlifecyclehooks: ^4.0.0
  jwt_decoder: ^2.0.1
  http_parser: ^4.0.2
  location: ^5.0.3
  connectivity_plus: ^5.0.2
  intl: ^0.18.1
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  local_auth: ^2.2.0
  open_street_map_search_and_pick: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1

dependency_overrides:
  http: ^0.13.5
  intl: 0.19.0



flutter_intl:
  enabled: true
