name: core
description: A new Flutter package project.
version: 1.0.0
homepage: www.github.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.1
  flutter_screenutil: ^5.9.1
  image_loader: ^1.10.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  rxdart: ^0.27.7
  form_field_validator: ^1.1.0
  dio_builder: ^3.0.4
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  json_annotation: ^4.9.0
  custom_progress_button: ^2.0.1
  flutter_spinkit: ^5.2.1
  simple_shared_pref: ^2.0.6
  transition_easy: ^1.0.8
  flutterlifecyclehooks: ^4.0.0
  jwt_decoder: ^2.0.1
  http_parser: ^4.0.2
  location: ^5.0.3
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  device_info_plus: ^10.1.0

  package_info_plus: ^8.0.2
  local_auth: ^2.2.0
  open_street_map_search_and_pick: ^0.1.1
  flutter_map: ^6.1.0
  lazy_load_scrollview: ^1.3.0
  easy_url_launcher: ^0.0.7
  flutter_zxing: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.8.0

dependency_overrides:
  http: ^0.13.5
  intl: 0.18.1



flutter_intl:
  enabled: true
