platform :ios, '13.0'

target 'Runner' do
 use_frameworks!
 pod 'FBSDKCoreKit'
 pod 'FBSDKLoginKit'
 pod 'AppCenter'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
